NaverCrawlingDjango/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crawling_main.urls')),
    path('index/', include('crawling_main.urls')),
    path('home/', include('crawling_main.urls')),
]

crawling_main/urls.py
from django.conf.urls import url, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'crawling_main'

urlpatterns = [
    url(r'^$', views.Crawling_main.as_view(), name='crawling_main'),
    url('result', views.result, name='result'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crawling_main/models.py
from django.db import models

# Create your models here.

crawling_main/views.py
from django.shortcuts import render, redirect

from django.views import View
from django.views import generic
from NaverCrawlingDjango import naver_crawler
from django import forms

# Create your views here.
class SearchForm(forms.Form):
    word = forms.CharField(max_length=10, widget=forms.TextInput)

class Crawling_main(generic.TemplateView):
    def get(self, request, *args, **kwargs):
        form = SearchForm()
        template_name = 'crawling_main/index.html'
        return render(request, template_name, {"form": form})

def result(request):
    template_name = 'crawling_main/result.html'
    word = request.POST['word']
    object = naver_crawler.fetch_naver_latest_data(word)
    result = object['result']
    title_list = object['title_list']
    naver_crawler.make_wordcloud(title_list)
    return render(request, template_name, {"result": result})

crawling_main/templates/crawling_main/index.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <title>검색기</title>
</head>
<body>
    <div class="jumbotron text-center">
      <h1>네이버 뉴스 검색기</h1>
      <p>검색어를 입력해주세요!</p>
        <form method="post" action="{% url 'crawling_main:result'}">
            {% csrf_token %}
            {{ form.as_p }}
            <!--<label for="word">검색어 </label>
            <div class="form-group">
              <input type="text" class="form-control" id="search_word" name="search_word" label="search_word">
            </div>-->
            <button type="submit" class="btn btn-primary">검색</button>
      </form>
    </div>
   <!-- <div class="col-md-12">
        <div class="container">
            <div class="list-group col">
                {% for list in result %}
                    <div class="list-group-item">
                        <a href={{ list.href }}>{{ list.title }}</a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>-->
</body>
</html>

crawling_main/templates/crawling_main/result.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <title>검색기</title>
</head>
<body>
    <div class="jumbotron text-center">
      <h1>네이버 뉴스 검색기</h1><br>
        <img src="{% static 'img/wordcloud.png'%}"><br><br>
        <button onclick="location.href='/'"  type="submit" class="btn btn-primary">돌아가기</button>
    </div>
   <div class="col-md-12">
        <div class="container">
            <div class="list-group col">
                {% for list in result %}
                    <div class="list-group-item">
                        <a href={{ list.link }}>{{ list.title }}</a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</body>
</html>